// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BulletMessage.proto

package com.GinElmaC.domain.protobuf;

public final class BulletMessage {
  private BulletMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_GinElmaC_domain_protobuf_PacketHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_GinElmaC_domain_protobuf_PacketHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_GinElmaC_domain_protobuf_PacketBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_GinElmaC_domain_protobuf_PacketBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023BulletMessage.proto\022\034com.GinElmaC.doma" +
      "in.protobuf\"x\n\014PacketHeader\022\016\n\006app_id\030\001 " +
      "\001(\007\022\013\n\003uid\030\002 \001(\006\022\r\n\005token\030\003 \001(\t\022\023\n\013compr" +
      "ession\030\004 \001(\005\022\022\n\nencryption\030\005 \001(\005\022\023\n\013mess" +
      "ageType\030\006 \001(\005\"\032\n\nPacketBody\022\014\n\004data\030\001 \001(" +
      "\tB \n\034com.GinElmaC.domain.protobufP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_GinElmaC_domain_protobuf_PacketHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_GinElmaC_domain_protobuf_PacketHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_GinElmaC_domain_protobuf_PacketHeader_descriptor,
        new java.lang.String[] { "AppId", "Uid", "Token", "Compression", "Encryption", "MessageType", });
    internal_static_com_GinElmaC_domain_protobuf_PacketBody_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_GinElmaC_domain_protobuf_PacketBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_GinElmaC_domain_protobuf_PacketBody_descriptor,
        new java.lang.String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
