// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: BulletMessage.proto
// Protobuf Java Version: 4.33.4

package com.GinElmaC.domain.protobuf;

/**
 * Protobuf type {@code com.GinElmaC.domain.protobuf.PacketHeader}
 */
@com.google.protobuf.Generated
public final class PacketHeader extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.GinElmaC.domain.protobuf.PacketHeader)
    PacketHeaderOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "PacketHeader");
  }
  // Use PacketHeader.newBuilder() to construct.
  private PacketHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PacketHeader() {
    token_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.GinElmaC.domain.protobuf.BulletMessage.internal_static_com_GinElmaC_domain_protobuf_PacketHeader_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.GinElmaC.domain.protobuf.BulletMessage.internal_static_com_GinElmaC_domain_protobuf_PacketHeader_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.GinElmaC.domain.protobuf.PacketHeader.class, com.GinElmaC.domain.protobuf.PacketHeader.Builder.class);
  }

  public static final int APP_ID_FIELD_NUMBER = 1;
  private int appId_ = 0;
  /**
   * <pre>
   * 业务id
   * </pre>
   *
   * <code>fixed32 app_id = 1;</code>
   * @return The appId.
   */
  @java.lang.Override
  public int getAppId() {
    return appId_;
  }

  public static final int UID_FIELD_NUMBER = 2;
  private long uid_ = 0L;
  /**
   * <pre>
   * 发送方的uid
   * </pre>
   *
   * <code>fixed64 uid = 2;</code>
   * @return The uid.
   */
  @java.lang.Override
  public long getUid() {
    return uid_;
  }

  public static final int TOKEN_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object token_ = "";
  /**
   * <pre>
   * 用户校验token，16字节
   * </pre>
   *
   * <code>string token = 3;</code>
   * @return The token.
   */
  @java.lang.Override
  public java.lang.String getToken() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 用户校验token，16字节
   * </pre>
   *
   * <code>string token = 3;</code>
   * @return The bytes for token.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenBytes() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPRESSION_FIELD_NUMBER = 4;
  private int compression_ = 0;
  /**
   * <pre>
   * 1字节，压缩方式标识，0-不压缩，1-gzip压缩
   * </pre>
   *
   * <code>int32 compression = 4;</code>
   * @return The compression.
   */
  @java.lang.Override
  public int getCompression() {
    return compression_;
  }

  public static final int ENCRYPTION_FIELD_NUMBER = 5;
  private int encryption_ = 0;
  /**
   * <pre>
   * 1字节，加密方式标识，0-不加密，1-aes加密
   * </pre>
   *
   * <code>int32 encryption = 5;</code>
   * @return The encryption.
   */
  @java.lang.Override
  public int getEncryption() {
    return encryption_;
  }

  public static final int MESSAGETYPE_FIELD_NUMBER = 6;
  private int messageType_ = 0;
  /**
   * <pre>
   * 2字节，消息类型，0-客户端登录，1-心跳，2-ack，3-强制下线，4-小直播间，5-大直播间，6-系统飘条消息，7-超管消息，8-礼物消息，9-集群机器连接消息，10-集群机器转发下行消息
   * </pre>
   *
   * <code>int32 messageType = 6;</code>
   * @return The messageType.
   */
  @java.lang.Override
  public int getMessageType() {
    return messageType_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (appId_ != 0) {
      output.writeFixed32(1, appId_);
    }
    if (uid_ != 0L) {
      output.writeFixed64(2, uid_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(token_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, token_);
    }
    if (compression_ != 0) {
      output.writeInt32(4, compression_);
    }
    if (encryption_ != 0) {
      output.writeInt32(5, encryption_);
    }
    if (messageType_ != 0) {
      output.writeInt32(6, messageType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (appId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(1, appId_);
    }
    if (uid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(2, uid_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(token_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, token_);
    }
    if (compression_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, compression_);
    }
    if (encryption_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, encryption_);
    }
    if (messageType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, messageType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.GinElmaC.domain.protobuf.PacketHeader)) {
      return super.equals(obj);
    }
    com.GinElmaC.domain.protobuf.PacketHeader other = (com.GinElmaC.domain.protobuf.PacketHeader) obj;

    if (getAppId()
        != other.getAppId()) return false;
    if (getUid()
        != other.getUid()) return false;
    if (!getToken()
        .equals(other.getToken())) return false;
    if (getCompression()
        != other.getCompression()) return false;
    if (getEncryption()
        != other.getEncryption()) return false;
    if (getMessageType()
        != other.getMessageType()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + APP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAppId();
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUid());
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    hash = (37 * hash) + COMPRESSION_FIELD_NUMBER;
    hash = (53 * hash) + getCompression();
    hash = (37 * hash) + ENCRYPTION_FIELD_NUMBER;
    hash = (53 * hash) + getEncryption();
    hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMessageType();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.GinElmaC.domain.protobuf.PacketHeader parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.GinElmaC.domain.protobuf.PacketHeader parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.GinElmaC.domain.protobuf.PacketHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.GinElmaC.domain.protobuf.PacketHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.GinElmaC.domain.protobuf.PacketHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.GinElmaC.domain.protobuf.PacketHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.GinElmaC.domain.protobuf.PacketHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.GinElmaC.domain.protobuf.PacketHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.GinElmaC.domain.protobuf.PacketHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.GinElmaC.domain.protobuf.PacketHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.GinElmaC.domain.protobuf.PacketHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.GinElmaC.domain.protobuf.PacketHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.GinElmaC.domain.protobuf.PacketHeader prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.GinElmaC.domain.protobuf.PacketHeader}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.GinElmaC.domain.protobuf.PacketHeader)
      com.GinElmaC.domain.protobuf.PacketHeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.GinElmaC.domain.protobuf.BulletMessage.internal_static_com_GinElmaC_domain_protobuf_PacketHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.GinElmaC.domain.protobuf.BulletMessage.internal_static_com_GinElmaC_domain_protobuf_PacketHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.GinElmaC.domain.protobuf.PacketHeader.class, com.GinElmaC.domain.protobuf.PacketHeader.Builder.class);
    }

    // Construct using com.GinElmaC.domain.protobuf.PacketHeader.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      appId_ = 0;
      uid_ = 0L;
      token_ = "";
      compression_ = 0;
      encryption_ = 0;
      messageType_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.GinElmaC.domain.protobuf.BulletMessage.internal_static_com_GinElmaC_domain_protobuf_PacketHeader_descriptor;
    }

    @java.lang.Override
    public com.GinElmaC.domain.protobuf.PacketHeader getDefaultInstanceForType() {
      return com.GinElmaC.domain.protobuf.PacketHeader.getDefaultInstance();
    }

    @java.lang.Override
    public com.GinElmaC.domain.protobuf.PacketHeader build() {
      com.GinElmaC.domain.protobuf.PacketHeader result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.GinElmaC.domain.protobuf.PacketHeader buildPartial() {
      com.GinElmaC.domain.protobuf.PacketHeader result = new com.GinElmaC.domain.protobuf.PacketHeader(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.GinElmaC.domain.protobuf.PacketHeader result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.appId_ = appId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.uid_ = uid_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.token_ = token_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.compression_ = compression_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.encryption_ = encryption_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.messageType_ = messageType_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.GinElmaC.domain.protobuf.PacketHeader) {
        return mergeFrom((com.GinElmaC.domain.protobuf.PacketHeader)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.GinElmaC.domain.protobuf.PacketHeader other) {
      if (other == com.GinElmaC.domain.protobuf.PacketHeader.getDefaultInstance()) return this;
      if (other.getAppId() != 0) {
        setAppId(other.getAppId());
      }
      if (other.getUid() != 0L) {
        setUid(other.getUid());
      }
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getCompression() != 0) {
        setCompression(other.getCompression());
      }
      if (other.getEncryption() != 0) {
        setEncryption(other.getEncryption());
      }
      if (other.getMessageType() != 0) {
        setMessageType(other.getMessageType());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              appId_ = input.readFixed32();
              bitField0_ |= 0x00000001;
              break;
            } // case 13
            case 17: {
              uid_ = input.readFixed64();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 26: {
              token_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              compression_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              encryption_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              messageType_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int appId_ ;
    /**
     * <pre>
     * 业务id
     * </pre>
     *
     * <code>fixed32 app_id = 1;</code>
     * @return The appId.
     */
    @java.lang.Override
    public int getAppId() {
      return appId_;
    }
    /**
     * <pre>
     * 业务id
     * </pre>
     *
     * <code>fixed32 app_id = 1;</code>
     * @param value The appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppId(int value) {

      appId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 业务id
     * </pre>
     *
     * <code>fixed32 app_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      appId_ = 0;
      onChanged();
      return this;
    }

    private long uid_ ;
    /**
     * <pre>
     * 发送方的uid
     * </pre>
     *
     * <code>fixed64 uid = 2;</code>
     * @return The uid.
     */
    @java.lang.Override
    public long getUid() {
      return uid_;
    }
    /**
     * <pre>
     * 发送方的uid
     * </pre>
     *
     * <code>fixed64 uid = 2;</code>
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(long value) {

      uid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送方的uid
     * </pre>
     *
     * <code>fixed64 uid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUid() {
      bitField0_ = (bitField0_ & ~0x00000002);
      uid_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object token_ = "";
    /**
     * <pre>
     * 用户校验token，16字节
     * </pre>
     *
     * <code>string token = 3;</code>
     * @return The token.
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 用户校验token，16字节
     * </pre>
     *
     * <code>string token = 3;</code>
     * @return The bytes for token.
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 用户校验token，16字节
     * </pre>
     *
     * <code>string token = 3;</code>
     * @param value The token to set.
     * @return This builder for chaining.
     */
    public Builder setToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      token_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户校验token，16字节
     * </pre>
     *
     * <code>string token = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearToken() {
      token_ = getDefaultInstance().getToken();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户校验token，16字节
     * </pre>
     *
     * <code>string token = 3;</code>
     * @param value The bytes for token to set.
     * @return This builder for chaining.
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      token_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int compression_ ;
    /**
     * <pre>
     * 1字节，压缩方式标识，0-不压缩，1-gzip压缩
     * </pre>
     *
     * <code>int32 compression = 4;</code>
     * @return The compression.
     */
    @java.lang.Override
    public int getCompression() {
      return compression_;
    }
    /**
     * <pre>
     * 1字节，压缩方式标识，0-不压缩，1-gzip压缩
     * </pre>
     *
     * <code>int32 compression = 4;</code>
     * @param value The compression to set.
     * @return This builder for chaining.
     */
    public Builder setCompression(int value) {

      compression_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 1字节，压缩方式标识，0-不压缩，1-gzip压缩
     * </pre>
     *
     * <code>int32 compression = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompression() {
      bitField0_ = (bitField0_ & ~0x00000008);
      compression_ = 0;
      onChanged();
      return this;
    }

    private int encryption_ ;
    /**
     * <pre>
     * 1字节，加密方式标识，0-不加密，1-aes加密
     * </pre>
     *
     * <code>int32 encryption = 5;</code>
     * @return The encryption.
     */
    @java.lang.Override
    public int getEncryption() {
      return encryption_;
    }
    /**
     * <pre>
     * 1字节，加密方式标识，0-不加密，1-aes加密
     * </pre>
     *
     * <code>int32 encryption = 5;</code>
     * @param value The encryption to set.
     * @return This builder for chaining.
     */
    public Builder setEncryption(int value) {

      encryption_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 1字节，加密方式标识，0-不加密，1-aes加密
     * </pre>
     *
     * <code>int32 encryption = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryption() {
      bitField0_ = (bitField0_ & ~0x00000010);
      encryption_ = 0;
      onChanged();
      return this;
    }

    private int messageType_ ;
    /**
     * <pre>
     * 2字节，消息类型，0-客户端登录，1-心跳，2-ack，3-强制下线，4-小直播间，5-大直播间，6-系统飘条消息，7-超管消息，8-礼物消息，9-集群机器连接消息，10-集群机器转发下行消息
     * </pre>
     *
     * <code>int32 messageType = 6;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public int getMessageType() {
      return messageType_;
    }
    /**
     * <pre>
     * 2字节，消息类型，0-客户端登录，1-心跳，2-ack，3-强制下线，4-小直播间，5-大直播间，6-系统飘条消息，7-超管消息，8-礼物消息，9-集群机器连接消息，10-集群机器转发下行消息
     * </pre>
     *
     * <code>int32 messageType = 6;</code>
     * @param value The messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageType(int value) {

      messageType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 2字节，消息类型，0-客户端登录，1-心跳，2-ack，3-强制下线，4-小直播间，5-大直播间，6-系统飘条消息，7-超管消息，8-礼物消息，9-集群机器连接消息，10-集群机器转发下行消息
     * </pre>
     *
     * <code>int32 messageType = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      bitField0_ = (bitField0_ & ~0x00000020);
      messageType_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.GinElmaC.domain.protobuf.PacketHeader)
  }

  // @@protoc_insertion_point(class_scope:com.GinElmaC.domain.protobuf.PacketHeader)
  private static final com.GinElmaC.domain.protobuf.PacketHeader DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.GinElmaC.domain.protobuf.PacketHeader();
  }

  public static com.GinElmaC.domain.protobuf.PacketHeader getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PacketHeader>
      PARSER = new com.google.protobuf.AbstractParser<PacketHeader>() {
    @java.lang.Override
    public PacketHeader parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PacketHeader> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PacketHeader> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.GinElmaC.domain.protobuf.PacketHeader getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

