// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: BulletMessage.proto
// Protobuf Java Version: 4.33.4

package com.GinElmaC.domain.protobuf;

@com.google.protobuf.Generated
public interface PacketBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.GinElmaC.domain.protobuf.PacketBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * json数据
   * </pre>
   *
   * <code>string data = 1;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <pre>
   * json数据
   * </pre>
   *
   * <code>string data = 1;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
