// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BulletMessage.proto

package com.GinElmaC.domain.protobuf;

public interface PacketHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.GinElmaC.domain.protobuf.PacketHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *业务id
   * </pre>
   *
   * <code>fixed32 app_id = 1;</code>
   * @return The appId.
   */
  int getAppId();

  /**
   * <pre>
   *发送方的uid
   * </pre>
   *
   * <code>fixed64 uid = 2;</code>
   * @return The uid.
   */
  long getUid();

  /**
   * <pre>
   *用户校验token，16字节
   * </pre>
   *
   * <code>string token = 3;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <pre>
   *用户校验token，16字节
   * </pre>
   *
   * <code>string token = 3;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <pre>
   *1字节，压缩方式标识，0-不压缩，1-gzip压缩
   * </pre>
   *
   * <code>int32 compression = 4;</code>
   * @return The compression.
   */
  int getCompression();

  /**
   * <pre>
   *1字节，加密方式标识，0-不加密，1-aes加密
   * </pre>
   *
   * <code>int32 encryption = 5;</code>
   * @return The encryption.
   */
  int getEncryption();

  /**
   * <pre>
   *2字节，消息类型，0-客户端登录，1-心跳，2-ack，3-强制下线，4-小直播间，5-大直播间，6-系统飘条消息，7-超管消息，8-礼物消息，9-集群机器连接消息，10-集群机器转发下行消息
   * </pre>
   *
   * <code>int32 messageType = 6;</code>
   * @return The messageType.
   */
  int getMessageType();
}
